----------------------------------------------------------
-- Start Create Data Table
----------------------------------------------------------
CREATE TABLE STOCK_INFO
(  		
	STOCK_NUM				TEXT		NOT NULL,
	ENG_NAME				TEXT		NULL,
	CHI_NAME				TEXT		NULL,
	MKT_CAP					INTEGER		NULL,
	BOARD_LOT				INTEGER		NULL,
	IS_HSI    				BOOLEAN    	NULL,
	LISTING_DATE			TEXT		NULL,
	ACTIVE   				BOOLEAN    	NOT NULL,
	LAST_MODIFIED_DATE     	TEXT		NOT NULL,
	PRIMARY KEY(STOCK_NUM)
);

CREATE TABLE STOCK_PRICE
(  		
	STOCK_NUM				TEXT		NOT NULL,
	STOCK_DATE				TEXT		NOT NULL,
	STOCK_DATE_SEQ			INTEGER		NULL,
	PRICE_OPEN				REAL		NOT NULL,
	PRICE_CLOSING			REAL		NOT NULL,
	PRICE_HIGHEST			REAL		NOT NULL,
	PRICE_LOWEST			REAL		NOT NULL,
	VOLUME					INTEGER		NOT NULL,
	IS_VALID			   	BOOLEAN    	NOT NULL,
	LAST_MODIFIED_DATE      TEXT		NOT NULL,
	PRIMARY KEY(STOCK_NUM, STOCK_DATE),
	FOREIGN KEY(STOCK_NUM) REFERENCES STOCK_INFO(STOCK_NUM)
);

CREATE INDEX STOCK_PRICE_IDX1 ON STOCK_PRICE(STOCK_NUM, STOCK_DATE_SEQ);

CREATE TABLE STOCK_ANALYSIS_DATA
(  		
	AD_TYPE					TEXT		NOT NULL,
	STOCK_NUM				TEXT		NOT NULL,
	STOCK_DATE				TEXT		NOT NULL,
	AD_VALUE				REAL		NOT NULL,
	LAST_MODIFIED_DATE      TEXT		NOT NULL,
	PRIMARY KEY(AD_TYPE, STOCK_NUM, STOCK_DATE),
	FOREIGN KEY(STOCK_NUM) REFERENCES STOCK_INFO(STOCK_NUM)
);

CREATE UNIQUE INDEX STOCK_ANALYSIS_DATA_IDX1 ON STOCK_ANALYSIS_DATA(AD_TYPE, STOCK_NUM, STOCK_DATE);


CREATE TABLE PATTERN_RESULT
(  		
	PATTERN_TYPE			TEXT		NOT NULL,
	STOCK_NUM				TEXT		NOT NULL,
	STOCK_DATE				TEXT		NOT NULL,
	FLAG_H_VOLUME			REAL		NOT NULL,
	LAST_MODIFIED_DATE      TEXT		NOT NULL,
	PRIMARY KEY(PATTERN_TYPE, STOCK_NUM, STOCK_DATE),
	FOREIGN KEY(STOCK_NUM) REFERENCES STOCK_INFO(STOCK_NUM)
);
